---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:20-alpine
    pull: always
    commands:
      - yarn install --immutable
      - yarn build
    env:
      - NODE_ENV=production

  - name: publish_linux-amd64
    when:
      ref:
        - refs/heads/master
    image: plugins/docker
    settings:
      repo: benscobie/student-loan-repayment-calculator
      dockerfile: docker/Dockerfile.linux.amd64
      tags: latest
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head

---
kind: signature
hmac: 3f84ad88c3ba53cb87dfe71d88bde2ac0f0b9ace7e9a6b8a8d9b46ec0731a925

...
