---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: node:lts-alpine
  commands:
    - npm install
    - npm run test:unit
      
- name: build
  image: node:lts-alpine
  commands:
    - npm run build

- name: publish_linux-amd64
  when:
    ref:
    - refs/heads/master
  image: plugins/docker
  settings:
    repo: benscobie/student-loan-repayment-calculator
    dockerfile: docker/Dockerfile.linux.amd64
    tags: latest
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password
---
kind: signature
hmac: c4170bf6458f19872fab217afa6e6c3a3e4b1d761f87b50d7fe8af3fe9c56cd6

...
