---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node:lts-alpine
  commands:
    - yarn install
    - yarn build

- name: publish_linux-amd64
  when:
    ref:
    - refs/heads/master
  image: plugins/docker
  settings:
    repo: benscobie/student-loan-repayment-calculator
    dockerfile: docker/Dockerfile.linux.amd64
    tags: latest
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password
---
kind: signature
hmac: 0deb73c65e2e2a022dd64752a173ac000242afa3648395b9e34f3b75ae8a2721

...
